from app.models.models import (
    Address,
    Category,
    Customer,
    CustomerSubscription,
    BillingCheckoutSession,
    Order,
    OrderItem,
    OrderPayment,
    PaymentMethod,
    Product,
    ProductCategory,
    ProductTag,
    Review,
    StripeCustomer,
    SubscriptionPlan,
    Tag,
)

MODEL_REGISTRY = (
    Customer,
    Address,
    Product,
    PaymentMethod,
    Category,
    Tag,
    ProductCategory,
    ProductTag,
    Review,
    Order,
    OrderItem,
    OrderPayment,
    StripeCustomer,
    BillingCheckoutSession,
    SubscriptionPlan,
    CustomerSubscription,
)

__all__ = [
    "Address",
    "BillingCheckoutSession",
    "Category",
    "Customer",
    "CustomerSubscription",
    "Order",
    "OrderItem",
    "OrderPayment",
    "PaymentMethod",
    "Product",
    "ProductCategory",
    "ProductTag",
    "Review",
    "StripeCustomer",
    "SubscriptionPlan",
    "Tag",
    "MODEL_REGISTRY",
]
